### ISSUE TITLE
Abandoned dependency

### ISSUE THREAD

**Issue by kabudu** [resquebundle/resque#36]
It appears that one of your dependencies ```chrisboulton/php-resque``` has been abandoned by the maintainer. There is a discussion about it here: https://github.com/chrisboulton/php-resque/issues/274

A relatively recent updated fork of that repository is: https://github.com/danhunsaker/php-resque. Would you consider updating your dependencies?

**Comment by PhilETaylor** [comment]
>A relatively recent updated fork of that repository is: https://github.com/danhunsaker/php-resque. Would you consider updating your dependencies?

That fork has not been worked on since Feb 2017 either...

**Comment by kabudu** [comment]
That was sort of why I used the word relatively, but it's had updates since chrisboulton abandoned it, and as far as I know, development hasn't ceased yet. 

If any of the updates are of interest to you, it might be worth it. I only mentioned it in case you didn't know.

**Comment by N4IR0** [comment]
Maybe you could change the resque dependency to https://github.com/resque/php-resque which is the official suggestion from chrisboulton/php-resque.

Additionally you could use a version instead of dev-master for this dependency. What do you think about that?

**Comment by PhilETaylor** [comment]
Im aware of this thanks :) 

I have been working on Symfony 4 compatibility in a branch https://github.com/resquebundle/resque/tree/symfony4-compat and will be looking for this dependency chain as part of that work. 

Im now running that symfony4-compat branch in production (well for the creation of jobs in our frontend layer) and Im working on getting it compatible with the actual running of jobs (but then easter came, then I got flu, and school holidays etc...) I'll be back on that soon... 

The problem is that "something" is still installing chrisboulton/php-resque regardless of setting OUR dependancy to resque/php-resque within this project (and my main production app) and I have not yet invested much time in finding out why as not much had changed in resque/php-resque since it was forked.
