### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by bhaktaraz** [resquebundle/resque#48]
Is there any plan to upgrade for symfony 5 support?

**Comment by PhilETaylor** [comment]
Yes once I have removed or resolved the issues with fosuser in my project, I’ll be moving it to S5

At that time I’ll be working on this bundle to bring it along too

**Comment by PhilETaylor** [comment]
As with millions of other projects, we are all waiting on FosUserBundle to be Symfony 5 compatible (as well as other dependencies) before migrating live projects, and as per millions of other developers, no paying scratch to itch means Ive not worked on S5 just yet.

The work to port the Jobs to use the container, and service dependency injection recently for compatibility with Symfony 4.4 means there should be little to do once this is finally compatible with Symfony 5 (It might already be compatible, Ive just not tested it ;-))

**Comment by bhaktaraz** [comment]
Yes its almost ready, need to update symfony version to composer requirements.

**Comment by monofone** [comment]
The only point it is not working out of the box is the Process component which has some BC issues on 5.0 in only accepting an array in the constructor.

So one should use `Process::fromShellCommandline(...)` instead of `new Process(...)`, this should work on 4.x and 5.x.

**Comment by PhilETaylor** [comment]
At the moment I don’t expect anything to work in Symfony 5 ;-)

There is a lot of changes I had to make in order to get a stable working solution 

I have it working locally in the office and then my Mac turned off and I can’t access it from home (lockdown/covid etc)

Once I can go to the office and reboot my Mac there I can push my changes into a branch for testing

At the moment I have the released version working in Symfony 4.4 in production 

Unfortunately most of my projects use fosuserbundle and so delayed moving to Symfony 5

**Comment by monofone** [comment]
Ah well, I don't have symfony 5.0 myself it was just the process component which I stumbled upon. And with this change it seems to work for me.

**Comment by PhilETaylor** [comment]
Closing this issue as I have stated Im working on symfony 5 support and the issues that created have been forked to other issues
